
/*
    CONSTANT FOR TABLE NAMES IN DATABASE
*/

export const TableListNames = {
    ALAMAT: 'ALAMAT',
    BAHAN: 'BAHAN',
    BONUS: 'BONUS',
    CUSTOMER: 'CUSTOMER',
    DETIL_TRANSAKSI: 'DETIL_TRANSAKSI',
    GAMBAR_PRODUK: 'GAMBAR_PRODUK',
    HAMPERS: 'HAMPERS',
    KARYAWAN: 'KARYAWAN',
    KUOTA_HARIAN: 'KUOTA_HARIAN',
    PENARIKAN_SALDO: 'PENARIKAN_SALDO',
    PENGADAAN_BAHAN: 'PENGADAAN_BAHAN',
    PENGELUARAN_LAIN: 'PENGELUARAN_LAIN',
    PENGGUNAAN_BAHAN_BAKU: 'PENGGUNAAN_BAHAN_BAKU',
    PENITIP_PRODUK: 'PENITIP_PRODUK',
    POIN: 'POIN',
    PRESENSI_KARYAWAN: 'PRESENSI_KARYAWAN',
    PRODUK: 'PRODUK',
    RELASI_BAHAN_RESEP: 'RELASI_BAHAN_RESEP',
    RELASI_PRODUK_HAMPERS: 'RELASI_PRODUK_HAMPERS',
    RESEP: 'RESEP',
    TRANSAKSI_PESANAN: 'TRANSAKSI_PESANAN',
    USERS: 'USERS',
    ROLE: 'ROLE'
}